### ISSUE TITLE
Keeping REMARKS field when generating ensembles

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/pdb-tools#10]
It would be nice to have an option to keep the pdb-specific REMARKS fields when generating an ensemble from single files with `pdb_mkensemble`. And also restore those when splitting such an ensemble. 

Would be a handy feature to reduce for example the number of files in HADDOCK directories without loosing the information in the REMARKS fields.

**Comment by JoaoRodrigues** [comment]
Valid point, but that unfortunately breaks the PDB format, where REMARKS should come first ahead of any coordinate data. Maybe a HADDOCK-specific version?

**Comment by amjjbonvin** [comment]
Yes - probably better we make our own HADDOCK-specific version.
