### ISSUE TITLE
Add option to pdb_tidy to only add TER between different chains

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/pdb-tools#101]
By default pdb_tidy adds TER statement for every break, within or between chains.

This might not always be desirable. Between chains is in principle always OK, but within the same chain not.
E.g. missing density in X-ray structures result in missing residues, but the gaps do not contain TER statements.

Those additional TER statement might cause third party software to handle those are real termini and add for example charges...

**Comment by JoaoRodrigues** [comment]
Won't `pdb_tidy -strict` help? The strict version only adds TERs between chains.

**Comment by amjjbonvin** [comment]
Must have read over it! :-)

But this should rather be the default since consistent with PDB

**Comment by joaomcteixeira** [comment]
Note, if we implement this update that would require changing pdb-tools to `v3` to keep Semantic Versioning 2.0 compatibility because it would imply a huge change in the `API -> result` flow. Maybe we should tag this issue to `v3`?
