### ISSUE TITLE
Remove REMARK and general info lines

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/pdb-tools#11]
I found myself today removing the `REMARK` and _info_ lines manually from a series of PDB files.  

Should there be a `pdb_delinfo.py` tool that keeps **only** lines from _coordinates_ and _connectivity_ ? If you agree, assign me for the task.

**Comment by JoaoRodrigues** [comment]
`pdb_keepcoord`? :)

**Comment by JoaoRodrigues** [comment]
We have 'sel' and 'del', usually for tools that do opposite tasks. Since there's no 'delcoord' and it doesn't make sense, I opted to call this one differently. I thought keep coord (as in, coordinate section) would be clear enough, apparently not :)

**Comment by amjjbonvin** [comment]
Confusing names to my opinion. `pdb_keepcoord` is clean and clear

**Comment by JoaoRodrigues** [comment]
I agree with @amjjbonvin , sorry .. The section of the file format is called 'coordinates'. At best we could call it `pdb_delremarks` but it's not so clear for those unfamiliar with the PDB format.
