### ISSUE TITLE
Issue with doctools.py

### ISSUE THREAD

**Issue by andrewsb8** [haddocking/pdb-tools#111]
**Describe the bug**
Was finished working on a new tool proposal. Went to run doctools.py to update documentation. The script does not run and I get different error messages for python and python3. I checked that this is not a package import issue in either version. 

**To Reproduce**
Steps to reproduce the behavior. Preferrably, a code snippet.
```
$ python doctools.py

  File "doctools.py", line 13
    print(template.read(), file=handle)
                               ^
SyntaxError: invalid syntax

----------------------------------------------------------------

$ python3 doctools.py

  File "doctools.py", line 25
    tool = importlib.import_module(f'pdbtools.{name}')
                                                    ^
SyntaxError: invalid syntax

```

**Expected behavior**
This file should execute and update documentation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Python Version: 2.7.12, 3.5.2

**Comment by joaomcteixeira** [comment]
Hi @andrewsb8 ,
I believe you are in the wrong repository. Anyway, nice to have you here :-) Cheers

**Comment by JoaoRodrigues** [comment]
I reopened this because `doctools.py` is indeed a script of ours, in `docs/`. @andrewsb8, could you upgrade to a more recent Py3 version (3.7+) and see if the error persist?

**Comment by andrewsb8** [comment]
It does not persist in python 3.9.7, thanks.

**Comment by JoaoRodrigues** [comment]
👍 looking forward to that new tool request :)

**Comment by joaomcteixeira** [comment]
Sorry @andrewsb8 for my lapse, i didn't really see the `pdbtools` in the paste text and realised about `doctools`. :exploding_head:

**Comment by andrewsb8** [comment]
No problem! Appreciate you reopening and getting back to me!
