### ISSUE TITLE
Implement `pdb_selmodel`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/pdb-tools#122]
**Is your tool request related to a problem? Please describe.**
When we have a multi-model ensemble we need to use `pdb_splitmodel` and then (in disk) find the appropriate model we want.

**Describe the solution you'd like**
`pdb_selmodel` would select a given `MODEL` in a ensemble or a range of models:

```
$ pdb_selmodel -1 1ccm.pdb
$ pdb_selmodel -1:5 1ccm.pdb
```

In case the input is not an ensemble it could instead just return the same pdb instead of an error, then it would not break any pipelines.

**Does any of the existing tools or a combination of them do what you want?**
No, but `pdb_splitmodel` + scripting does the trick.

**Comment by joaomcteixeira** [comment]
We have talked about this in the past. I agree with having this tool, I
also find it very useful.
