### ISSUE TITLE
Possible bug in Molprobity

### ISSUE THREAD

**Issue by Mr-MOPAC** [haddocking/pdb-tools#125]
For one of the systems, good.pdb, in "good and test pdb files.zip", attached, MolProbity at http://molprobity.biochem.duke.edu/ gives correct results for clashes, for the other, a similar system, test.pdb, MolProbity gives incorrect results.  For both systems the <file>_clean_trimmed.pdb was used.  If the "Add hydrogens" option was used, both systems gave correct results.

I've struggled to simplify these systems, and hope that they are of use in debugging.  If I've made a mistake, please let me know,

Jimmy Stewart (MrMOPAC)

[good and test pdb files.zip](https://github.com/haddocking/pdb-tools/files/8137253/good.and.test.pdb.files.zip)
.

**Comment by JoaoRodrigues** [comment]
Hi @Mr-MOPAC, could you be more specific about the problem you are facing? I'm not sure if you are in the right repository.

**Comment by Mr-MOPAC** [comment]
Hi João,
I've been using Molprobity to estimate how good my prediction of protein geometries is.  I use the clashscore as the criterion.  This has worked well until I started examining a zinc endoprotease, specifically PDB entry 1C7K. Because I work with hydrogenate systems, I use the hydrogenation in the PDB file fed into Molprobity, that is I use the "<file>.pdb File (modified) uploaded by user" and do NOT use the "Add hydrogens" option.  If I use the "<file>_1_trimmed.pdb" option, and use "Add hydrogens" the problem I'm reporting does not occur.
Because the problem is so specific, I started with two proteins, Crambin 1CBN and Zinc Protease 1C7K, and focused on an ARG in both systems.  The error shows up in 1C7K and does not show up in 1CBN. By progressively trimming the systems, I ended up with exactly one residue in each system. Both these systems have the same atoms, in the same order, and with the same atom labels.  So the only difference is in the geometries, which are also similar.  But one, labeled "good.pdb" runs correctly in Molprobity, while the other, "test.pdb" gives nonsense results.
If you run "test.pdb" using Molprobity, and use the option "test_clean.pdb" then calculate the clashscores, the error can be duplicated.  This error does not occur when "good.pdb" is used.
I hope this is what you wanted.  If not, please advise me.
Jimmy





    On Thursday, February 24, 2022, 04:46:52 PM MST, João Rodrigues ***@***.***> wrote:  
 
 


Hi @Mr-MOPAC, could you be more specific about the problem you are facing? I'm not sure if you are in the right repository.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JoaoRodrigues** [comment]
Hi Jimmy,

I think you have the wrong repository. `pdb-tools` is a suite of scripts to do very simple manipulations of PDB files - we don't have any interface to Molprobity or any functionality to add hydrogen atoms to a structure. Maybe you should reach out to the developers of Molprobity, as this seems to be an issue with their server?

**Comment by Mr-MOPAC** [comment]
Thank you, João,
I was unsure of who to contact - now I'll try contacting the developers of Molprobity.
I appreciate your advice,
Jimmy 

    On Thursday, February 24, 2022, 10:53:23 PM MST, João Rodrigues ***@***.***> wrote:  
 
 


Hi Jimmy,

I think you have the wrong repository. pdb-tools is a suite of scripts to do very simple manipulations of PDB files - we don't have any interface to Molprobity or any functionality to add hydrogen atoms to a structure. Maybe you should reach out to the developers of Molprobity, as this seems to be an issue with their server?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
