### ISSUE TITLE
Bug in the `pdb-tools` website

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/pdb-tools#128]
A strange bug related to the minimal theme. Curious is I have never encountered that bug before in my many github minimal themes pages. But the bug is there indeed. I can also see it -> Chrome Version 100.0.4896.75 (Official Build) (64-bit)

![Peek 2022-04-11 11-19](https://user-images.githubusercontent.com/2901810/162892342-a9c4207a-05cd-4475-a457-64906bc1512f.gif)

Found by @menoliu

**Comment by amjjbonvin** [comment]
Is it reproducible with other browsers?
