### ISSUE TITLE
pdb_merge not adding END statement

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/pdb-tools#149]
**Describe the bug**

When using `pdb_merge`, TER statement are added between the merged chains, but the END statement is missing

**Expected behavior**

The output PDB should end with an END statement

**Comment by joaomcteixeira** [comment]
Sorry, this one passed unnoticed. I suggest we keep with what's referred to in the docs and pipe the results to `pdb_tidy` as the latter handles `END`, `TER`, etc, correctly (and it's quite an intricate logic also).

```
The contents are not sorted and no lines are deleted (e.g. END, TER
statements) so we recommend piping the results through `pdb_tidy.py`.
```
