### ISSUE TITLE
Add listing/glossary of the tools to our documentation

### ISSUE THREAD

**Issue by JoaoRodrigues** [haddocking/pdb-tools#24]
It could be useful to have a list of all the tools we have and a very small description (even pulled directly from their own documentation), so that people can see quickly what's out there.

**Comment by mtrellet** [comment]
We could have a look at this project to automate things a bit: https://github.com/NiklasRosenstein/pydoc-markdown

Of course sphinx does it quite nicely as well but I'm not sure it does combine well with jekyll and I'm not sure we want to go down that way either...

**Comment by JoaoRodrigues** [comment]
Fixed by #45, #46, and #47 !

**Comment by joaomcteixeira** [comment]
Hehe, just for fun on pulling docstrings automatically, @mtrellet @JoaoRodrigues 

a long time ago I did this using recursion as an exercise. I don't even recall in which state I left it :thinking:

https://github.com/joaomcteixeira/HyperSimpleDocstring2Md

**Comment by JoaoRodrigues** [comment]
Oh now you tell me...

**Comment by mtrellet** [comment]
Oh super nice @joaomcteixeira , I steal that!

Sorry for you @JoaoRodrigues ...

**Comment by joaomcteixeira** [comment]
> Oh now you tell me...

you were too fast on the PRs :100: 

@mtrellet c00l! Thx! I don't recall well the state of it, but it was working. Have a look let me know you feedback. Last commit 15 months go :fallen_leaf:
