### ISSUE TITLE
Dead link for RCSB PDB format

### ISSUE THREAD

**Issue by mtrellet** [haddocking/pdb-tools#27]
**Describe the bug**
The RCSB URL provided in the docstrings of [`pdb_validate`](../blob/master/pdbtools/pdb_validate.py) to reference a proper ATOM record format no longer exists.

**To Reproduce**
Access http://deposit.rcsb.org/adit/docs/pdb_atom_format.html

**Expected behavior**
Proper web page with ATOM record of PDB described

**Proposed substitution**
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

**Comment by mtrellet** [comment]
Better idea for the new URL?

**Comment by JoaoRodrigues** [comment]
Sounds good!
