### ISSUE TITLE
pdb_selres should allow for selecting a unique residue

### ISSUE THREAD

**Issue by mtrellet** [haddocking/pdb-tools#28]
**Describe the bug**
When using the same residue ID as an argument, `pdb_selres` script returns the following error:
```ERROR!! Start (11) cannot be larger than end (11)```

**To Reproduce**

```
pdb_fetch.py 4G6K | pdb_selres -11:11
ERROR!! Start (11) cannot be larger than end (11)
```

**Expected behavior**
Residue(s) with ID 11 should be selected and returned

**Desktop (please complete the following information):**
 - OS: MacOSX Mojave 10.14.3
 - Python Version: all

**Comment by mtrellet** [comment]
I'd suggest we allow `pdb_selres` to select a unique residue since, as far as I know, we do not have similar script to do so.

**Comment by JoaoRodrigues** [comment]
Good catch. Could you add a test for that as well to `test_pdb_selres`? Your commit (why not  PR?) looks good!
