### ISSUE TITLE
RFE: enhance pdb_selres to allow selection of random residue list

### ISSUE THREAD

**Issue by truatpasteurdotfr** [haddocking/pdb-tools#34]
**Is your tool request related to a problem? Please describe.**
I would like to select any list of residue from a pdb file.

**Describe the solution you'd like**

pdb_selres 1,10,43,8 my.pdb would ouput the 1,8,10 and 43rd residues from the pdb file.

**Does any of the existing tools or a combination of them do what you want?**
I can iterate with pdb_selres and extract each number in  loop and concatenate the resulting output files

**Remember**
Each `pdb-tools` should do one and one job only. If you have to describe what you want using an _and_, probably it is the job for at least _two_ tools. We want simple tools that can be combined, for flexibility.

**Comment by mtrellet** [comment]
Hello @truatpasteurdotfr, thanks for the suggestion!

Sounds like a common usage for the tool. In the meantime, the overhead to loop over the desired residue IDs is not much. What's your take on this @JoaoRodrigues, @joaomcteixeira ?

**Comment by JoaoRodrigues** [comment]
On it, thanks! For some reason I was not getting email notifications ...

**Comment by JoaoRodrigues** [comment]
This has been addressed by #37 

You can now do what you request, except that it isn't the 1st, 2nd, 3rd residues, but residue numbers 1, 2, and 3 (this was the original desired behavior anyway).
