### ISSUE TITLE
enhancement of pdb_wc

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/pdb-tools#53]
After #51, we can consider increasing the detail of `the pdb_wc` report to enhance the user experience of both the command-line user as well as the pdb-tools web interface @brianjimenez is developing.

If I recall properly, we discussed altogether in the emails that `pdb_wc` could also report, for example, on the chain IDs, residue number ranges and atom ranges. This would facilitate the interaction of the user with the other tools such as `pdb_chain`.

I take no full credit for this idea, *I am just registering an idea discussed by all which I found really interesting*.

@brianjimenez how could this be integrated in the web interface? Do you find it useful for `pdb_wc` to do this? Or should it be another tool to do it?

I can take this if you all agree with the implementation.

**Comment by brianjimenez** [comment]
At the moment, not using `pdb_wc` for parsing, but `BioPython` library as we already have it installed for other services. I think `pdb_wc` should be focused on what users at cli level would need, no need to couple it for the moment with the web front-end.

**Comment by JoaoRodrigues** [comment]
#51 does this already: e.g. `pdb_wc -c` it prints the chain details. The default `pdb_wc` prints an overall summary, which I thought was cleaner than having a very long output. Did you mean something different?

**Comment by joaomcteixeira** [comment]
Ah! I completely missed that.

I suggest changing slightly the documentation, currently it reads:

"Several options are available to produce **only** partial summaries:"

This *only* word mislead me. My bad. It led me to think that those options would reduce the default report instead of enhancing or providing more detail for specific sections.

Could we changed it to?:

"Several options are available to produce **detailed** partial summaries:"

**Comment by JoaoRodrigues** [comment]
Fixed by #59.

We should also think of a github action to update the webpage automatically..
