### ISSUE TITLE
input PDB file

### ISSUE THREAD

**Issue by fedeserral** [haddocking/pdb-tools#73]
Hi! I am new using this tool. I just wanna know if a list of PDB IDs can be used as input file or I should use just one at time. 

Thanks!!

**Comment by joaomcteixeira** [comment]
Hi @fedeserral 

It depends, some tools accept several pdb files such as `pdb_merge`. Other accept only one such as `pdb_chain`.

You can view each tool help with `pdb_chain -h` for example.

Assuming you are on Linux (or bash), you can do the following to use a tool on several PDBs, say you want to change the chain ids of every PDB file in a folder to `new_*` files, navigate to that folder, then (I am assuming here you know a bit of bash):

```
for PDB in *.pdb; do pdb_chain -A $PDB > new_$PDB; done
```

If you are on Windows @JoaoRodrigues can help you :wink:

**Comment by JoaoRodrigues** [comment]
Hi @fedeserral 

As @joaomcteixeira said, most tools work on one PDB file at a time, except for a few exceptions. You can use a for-loop in BASH for example do get multiple files processed. If you are on windows, I recommend you get the Windows Subsystem for Linux (WSL) installed, or alternatively download and install cmder (full version). You'll get a proper BASH shell with full interoperability with your Windows file system.
