### ISSUE TITLE
Coot can't open the output file of pdb_merge 

### ISSUE THREAD

**Issue by 1ut** [haddocking/pdb-tools#94]
```
pdb_merge a.pdb b.pdb ... > output.pdb
```

```
pdb_merge a.pdb b.pdb ... | pdb_tidy > output.pdb
```

I generated the output.pdb file like above(url of file: https://drive.google.com/file/d/1INUdZfA8dEoe40k0v4IA32iFHwI_JRno/view?usp=sharing)
When I tried to open output.pdb using coot, it only showed the content of a.pdb file above. Howerver when I used Chimera, it showed the content of output.pdb. Next I saved the output.pdb file in chimera to another file (url of file: https://drive.google.com/file/d/1lpY40CnG3mXGZiXwQ96IBeNWYMN3Rkhd/view?usp=sharing). When opening it by coot, the content of output.pdb was shown. 

I want to know how to generate file that can be used in coot by using this tool directly. 
Thanks in advance. 

Coot version: 0.9.3

**Comment by joaomcteixeira** [comment]
Hi @1ut 

*I am removing the label `bug` until proven it is really a bug*.

I am not aware of the Coot specifications but, you can try to remove the comment lines as they appear to be the main difference between the PDBs you sent, try:

```
pdb_merge a.pdb b.pdb ... | pdb_keepcoord | pdb_tidy > output.pdb
```

If that is not a problem to you, could you send us the original `a.pdb` and `b.pdb` so we can understand if there is really a bug? If those are private data of yours, never mind, we can try to sort it out together with you from here.

Cheers, and thanks for writing.

**Comment by 1ut** [comment]
Pdb_keepcoord solved the problem. Thanks for prompt reply. 

```
pdb_merge a.pdb b.pdb ... | pdb_keepcoord | pdb_tidy > output.pdb
```
